apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-db-argocd-kustomize-kyverno-grafana-loki-tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/exea-centrum/website-db-argocd-kustomize-kyverno-grafana-loki-tempo.git
    targetRevision: main
    path: k8s/base
    kustomize:
      images:
      - name: ghcr.io/exea-centrum/website-db-argocd-kustomize-kyverno-grafana-loki-tempo
        newTag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: davtrowebdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
