apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-db-argocd-kustomize-kyverno-grafana-loki-tempo
  namespace: argocd
spec:
  destination:
    namespace: davtrowebdb
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/youruser/website-db-argocd-kustomize-kyverno-grafana-loki-tempo.git
    targetRevision: main
    path: k8s/base
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
