apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-db-argocd-kustomize-kyverno-grafana-loki-tempo
  namespace: argocd
  labels:
    app.kubernetes.io/name: website-db-argocd-kustomize-kyverno-grafana-loki-tempo
    app.kubernetes.io/instance: website-db-argocd-kustomize-kyverno-grafana-loki-tempo
spec:
  project: default
  source:
    repoURL: https://github.com/exea-centrum/website-db-argocd-kustomize-kyverno-grafana-loki-tempo.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: davtrowebdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
