apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: davtrowebdb
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        args:
          - "-config.file=/etc/loki/local-config.yaml"
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: wal-storage
          mountPath: /wal
        - name: loki-data
          mountPath: /loki
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: wal-storage
        emptyDir: {}
      - name: loki-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: davtrowebdb
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
