apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-test
  namespace: davtrowebdb
spec:
  template:
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8.8
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "False"
            - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
              value: "False"
            - name: PGADMIN_PORT
              value: "5050"
          ports:
            - containerPort: 5050
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # Bez volumeMounts i securityContext
