apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: davtrowebdb
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m
    compactor:
      compaction:
        block_retention: 1h
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: davtrowebdb
spec:
  selector:
    app: tempo
  ports:
    - port: 3200
      targetPort: 3200
