apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: $NAMESPACE
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095
      
    distributor:
      receivers:
        otlp:
          protocols:
            http:
            grpc:
            
    ingester:
      max_block_duration: 5m
      trace_idle_period: 10s
      
    compactor:
      compaction:
        block_retention: 1h
        compacted_block_retention: 10m
        
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        pool:
          max_workers: 100
          queue_depth: 10000
