apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: davtrowebdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        volumeMounts:
          - name: config
            mountPath: /etc/loki
        ports:
          - containerPort: 3100
      volumes:
        - name: config
          configMap:
            name: loki-config
