apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: davtrowebdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:2.47.0
        volumeMounts:
          - name: config
            mountPath: /etc/prometheus
        ports:
          - containerPort: 9090
      volumes:
        - name: config
          configMap:
            name: prometheus-config
