apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: davtrowebdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:1.6.0
        volumeMounts:
          - name: config
            mountPath: /etc/tempo
        ports:
          - containerPort: 3200
      volumes:
        - name: config
          configMap:
            name: tempo-config
